### ISSUE TITLE
[BUG] Wrong board image download

### ISSUE THREAD

**Issue by kr4xkan** [rdeepak2002/reddit-place-script-2022#226]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

I'm pretty sure the downloaded image is wrong

## To Reproduce

Steps to trigger the bug:

I enabled new_img.show()

## Expected behavior

Have the board but not offsetted

## Additional context

![img](https://user-images.githubusercontent.com/24639535/161422856-167efdc3-72f6-498b-ae04-7abff4e670b8.png)

**Comment by kr4xkan** [comment]
Oh and that implies wrong information given by `get_unset_pixel` if you are drawing on the right side of the screen (and prolly also on the left side)

**Comment by Zinston** [comment]
+1 on this one. I set my coordinates for someplace in the right half and it seems to just "modulo" them so I'm drawing in the left half.

**Comment by funwithtriangles** [comment]
I'm drawing in the left half but sometimes detecting wrong pixel info, perhaps related...

**Comment by Plantchant** [comment]
I know it's not ideal, but I'm too tired to check through code right now. Here's the last time I worked on it and I believe this problem was fixed at the time.
https://github.com/rdeepak2002/reddit-place-script-2022/tree/c312857020e586884ec7f399e743bca3ec00806d

**Comment by JAKONL** [comment]
Hey @kr4xkan - are you able to share some of the debug logs when you experience this? There should be some pretty thorough messaging in there to help us figure it out.

**Comment by kr4xkan** [comment]
My bad this got fixed by #209

**Comment by JAKONL** [comment]
Are @Zinston or @funwithtriangles still experiencing this after pulling that update?

**Comment by Zinston** [comment]
@JAKONL Yes actually I had pulled just before commenting so that fix should have been with it.

**Comment by Zinston** [comment]
Apologies it must have been an issue with my pythonanywhere env because I just tried again locally and had no issue!

**Comment by funwithtriangles** [comment]
I'm still having issues with wrong pixel values being detected

**Comment by funwithtriangles** [comment]
I worked it out, images were being stitched together in the wrong order sometimes, fix here:
https://github.com/rdeepak2002/reddit-place-script-2022/pull/241
